spring.application.name=decision-engine
engine.MIN_SUM=1000.0
engine.MAX_SUM=10000.0
engine.MIN_PERIOD=12
engine.MAX_PERIOD=60

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.h2.console.enabled=true

